spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cp_db
    username: postgres
    password: mohamed29141002
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
